-- Seed the fixed modality list and every rating scale's descriptions.
-- Both tables are admin-editable in-app; this just gives you a starting point.

insert into modalities (key, label, sort_order) values
  ('squat', 'Squat', 1),
  ('hinge', 'Hinge', 2),
  ('push_upper', 'Push (Upper)', 3),
  ('pull_upper', 'Pull (Upper)', 4),
  ('push_lower', 'Push (Lower)', 5),
  ('pull_lower', 'Pull (Lower)', 6),
  ('drag', 'Drag', 7),
  ('carry', 'Carry', 8),
  ('brace', 'Brace', 9),
  ('twist', 'Twist', 10),
  ('jump', 'Jump', 11),
  ('land', 'Land', 12);

insert into rating_descriptions (scale_key, rating, description) values
  ('recovery', 10, 'Ready to improve performance with increased external load'),
  ('recovery', 9, 'Ready to sustain performance with increased external load'),
  ('recovery', 8, 'Ready to improve performance with similar external load'),
  ('recovery', 7, 'Ready to sustain performance with similar external load'),
  ('recovery', 6, 'Ready to sustain performance with decreased external load'),
  ('recovery', 5, 'Need to scale back performance with similar external load'),
  ('recovery', 4, 'Need to scale back performance with decreased external load'),
  ('recovery', 3, 'Need to significantly scale back performance and load'),
  ('recovery', 2, 'Need to perform alternate exercises'),
  ('recovery', 1, 'Unable to train'),

  ('session_fatigue', 10, 'Unable to complete training'),
  ('session_fatigue', 9, 'Able to complete, but may be difficult to recover'),
  ('session_fatigue', 8, 'Pushed more than necessary, but will be able to recover'),
  ('session_fatigue', 7, 'Probably an adequate level of exertion'),
  ('session_fatigue', 6, 'Probably slightly less than adequate level of exertion'),
  ('session_fatigue', 5, 'Lower level of exertion than required'),
  ('session_fatigue', 4, 'Deload'),
  ('session_fatigue', 3, 'Little fatigue'),
  ('session_fatigue', 2, 'No fatigue'),
  ('session_fatigue', 1, 'No activity'),

  ('pain_intensity', 10, 'Emergency room'),
  ('pain_intensity', 9, 'Painful new injury'),
  ('pain_intensity', 8, 'Painful reinjury'),
  ('pain_intensity', 7, 'Minor new injury'),
  ('pain_intensity', 6, 'Aggravated recurring injury'),
  ('pain_intensity', 5, 'Persistent, moderate pain'),
  ('pain_intensity', 4, 'Persistent, minor pain'),
  ('pain_intensity', 3, 'Minor, momentary pain'),
  ('pain_intensity', 2, 'Stiffness or soreness'),
  ('pain_intensity', 1, 'No pain'),

  ('session_focus', 10, 'High focus throughout session'),
  ('session_focus', 9, 'High focus for most of the session'),
  ('session_focus', 8, 'Adequate focus; stuck with the plan'),
  ('session_focus', 7, 'Adequate focus; minor technique errors'),
  ('session_focus', 6, 'Had to lower intensity due to technique'),
  ('session_focus', 5, 'Had to lower volume due to technique'),
  ('session_focus', 4, 'Had to lower density due to technique'),
  ('session_focus', 3, 'Had to modify training session'),
  ('session_focus', 2, 'Very poor focus; cut training short'),
  ('session_focus', 1, 'Incapable of focusing; did not train'),

  ('sleep_quality', 10, 'Feel refreshed'),
  ('sleep_quality', 9, 'Feel rested'),
  ('sleep_quality', 8, 'Somewhat rested'),
  ('sleep_quality', 7, 'Somewhat tired'),
  ('sleep_quality', 6, 'Tired'),
  ('sleep_quality', 5, 'Groggy'),
  ('sleep_quality', 4, 'No energy'),
  ('sleep_quality', 3, 'Difficulty staying awake'),
  ('sleep_quality', 2, 'Extreme difficulty staying awake'),
  ('sleep_quality', 1, 'No sleep'),

  ('energy_level', 10, 'High energy all day'),
  ('energy_level', 9, 'High energy most of the day'),
  ('energy_level', 8, 'Enough energy all day'),
  ('energy_level', 7, 'Enough energy most of the day'),
  ('energy_level', 6, 'Low energy for most of the day'),
  ('energy_level', 5, 'Tired for most of the day'),
  ('energy_level', 4, 'Tired all day'),
  ('energy_level', 3, 'Difficulty staying awake most of the day'),
  ('energy_level', 2, 'Difficulty staying awake all day'),
  ('energy_level', 1, 'Had to go back to sleep'),

  ('stress_management', 10, 'Stress-free all day'),
  ('stress_management', 9, 'Stress-free most of the day'),
  ('stress_management', 8, 'Low-stress most of the day'),
  ('stress_management', 7, 'Low-stress all day'),
  ('stress_management', 6, 'Medium stress most of the day'),
  ('stress_management', 5, 'Medium stress all day'),
  ('stress_management', 4, 'High stress most of the day'),
  ('stress_management', 3, 'High stress all day'),
  ('stress_management', 2, 'Unmanageable stress most of the day'),
  ('stress_management', 1, 'Unmanageable stress all day'),

  ('focus_level', 10, 'High focus all day'),
  ('focus_level', 9, 'High focus most of the day'),
  ('focus_level', 8, 'Adequate focus all day'),
  ('focus_level', 7, 'Adequate focus most of the day'),
  ('focus_level', 6, 'Adequate focus when needed'),
  ('focus_level', 5, 'Inadequate focus most of the day'),
  ('focus_level', 4, 'Inadequate focus all day'),
  ('focus_level', 3, 'Distracted most of the day'),
  ('focus_level', 2, 'Distracted all day'),
  ('focus_level', 1, 'Incapable of focusing'),

  ('work_life_balance', 10, 'High margin at work and home'),
  ('work_life_balance', 9, 'Low margin at work and home'),
  ('work_life_balance', 8, 'Margin at home'),
  ('work_life_balance', 7, 'Margin at work'),
  ('work_life_balance', 6, 'No margin'),
  ('work_life_balance', 5, 'Home interferes with work'),
  ('work_life_balance', 4, 'Work interferes with home'),
  ('work_life_balance', 3, 'Failure at work'),
  ('work_life_balance', 2, 'Failure at home'),
  ('work_life_balance', 1, 'Failure at work and home'),

  ('noise', 5, 'No noise (other than white noise)'),
  ('noise', 4, 'Noise had no effect'),
  ('noise', 3, 'Noise is disruptive'),
  ('noise', 2, 'Noise woke me up'),
  ('noise', 1, 'Too noisy to sleep'),

  ('light', 5, 'Dark'),
  ('light', 4, 'Low light had no effect'),
  ('light', 3, 'Low light delayed sleep'),
  ('light', 2, 'Bright light delayed sleep'),
  ('light', 1, 'Too bright to sleep'),

  ('temperature', 5, 'Comfortable when covered'),
  ('temperature', 4, 'Comfortable with sheet only'),
  ('temperature', 3, 'Comfortable if uncovered'),
  ('temperature', 2, 'Heat delayed sleep'),
  ('temperature', 1, 'Too hot to sleep'),

  ('humidity', 5, 'Comfortable'),
  ('humidity', 4, 'Not ideal, but no effect on sleep'),
  ('humidity', 3, 'Humidity exacerbated temperature'),
  ('humidity', 2, 'Dryness or humidity delayed sleep'),
  ('humidity', 1, 'Too dry or humid to sleep');
